- src/pure.ts
- Parse comma separated appDiv string
- Populate requiresOptIn associated permits with false state
Implement expected functionality
> chore(pure): appDiv + optIn

- package-lock.json
- package.json
- src/index.ts
- src/pure.ts
> export init
> match experience type
> fix(init): export init + fix type

- rollup.config.js
> Window context
-  [x] I have informed stakeholders of my changes.
> fix(rollup): window

- package-lock.json
- package.json
- rollup.config.js
- src/internal/logging.ts
> Explicitly require log level
> fix(build): loglevel

- package-lock.json
- package.json
- src/pure.ts
- test/rights.test.ts
> Pass in baseUrl from config to request
> fix(ketchapi): pass in base url

- src/index.ts
- src/pure.ts
> Pass in jurisdiction and environment to ketch instance
> pollIdentity on correct ketch instance
> fix(boot): pass in bootstrap info to ketch constructor

- src/index.ts
> Set explicit this of ketch instance in entry point
> fix(entrypoint): explicit this

- src/index.ts
Fix init so it runs through queue first.
> fix: make init load config before processing queue

- src/pure.ts
RegisterPlugin needs to add functions. Previous syntax was getting confused for tertiary expressions ?:
> fix: register plugin actually registering executable functions

- package-lock.json
- package.json
Pick up latest ketch-web-api changes
To be tested in DEV
N/A
> chore(deps): bump ketch-web-api dep

- src/pure.ts
Correct logic for checking if identities match in pollIdentity
> fix(pollid): correct id match

- package-lock.json
- package.json
> fix(canonicalPurpose): add

- src/pure.ts
Update changed variable to create disclosure permits when getting consent
There is another update required in lanyard
> fix(getConsent): create disclosure permits

- package-lock.json
- package.json
- src/index.ts
- src/pure.ts
Register willShowExperience and experienceHidden
Call willShowExperience and experience at appropriate times
> fix(experience): update hooks

- src/pure.ts
Update route to use shorelinev2
=
> fix(shorelinev2): use shoreline v2

- package-lock.json
- package.json
- src/internal/parameters.ts
- src/pure.ts
- test/consent.test.ts
- test/rights.test.ts
Add jurisdicitonCode in getConsent request
Add swb_show parameter to override showing experiences if not already shown in session
Update tests
> fix(getConsent): add jursidictionCode + swb_show override

- package-lock.json
- package.json
- src/pure.ts
Support consent response with allowed or without to support shoreline v1 and v2
> fix(getConsent): optional allowed

- package-lock.json
- package.json
- src/pure.ts
Update client consent object before showing experience
> fix(getConsent): update client consent object before showing experience

- src/index.ts
Wait for getConsent to return to begin polling identities
> fix(pollIdentity): wait for consent returned

- src/pure.ts
- test/preferences.test.ts
> fix(preference): wait for consent

- src/pure.ts
> fix(lanyard): load by language

- src/pure.ts
> fix(consent): handle empty merge

- src/pure.ts
Ensure session purposes in config
> fix(consent): session confirm in config

- src/pure.ts
Fix config purpose validation when merging session consent
> fix(consent): fix validate config

- src/pure.ts
- test/identity.test.ts
Found `0` sent by customer as an id that did not represent a real user
Filter `0` and other falsey values
Added unit tests
> fix(identity): filter falsey and `0` values

- package-lock.json
- src/pure.ts
- test/environment.test.ts
Correct pattern match length
Unit test
> fix(environment): correct pattern match

- src/internal/cookie.ts
Set cookie with root domain
If set fails this is likely because the domain is a suffix which browsers do not allow
Append next element onto root domain and retry
> fix(cookie): set root domain progressively

- src/internal/cookie.ts
> fix(cookie): return setCookie after domain match

- src/internal/cookie.ts
> fix(cookie): return resolve

- src/pure.ts
- test/identity.test.ts
> convert number window type identity variable to string
> tested on local with unit tests
> Fix [KD-3042](https://ketch-com.atlassian.net/browse/KD-3042)
> chore: convert number window type identity variable to string

- src/pure.ts
Handle shoreline url with /web/v2 ending to not duplicate
> fix(shoreline): url

- .github/workflows/ci.yml
> chore: bump ci

- src/pure.ts
Handle https://global.ketchcdn.com/transom/route/switchbit/lanyard/vara_labs/lanyard-preferences.en.js
> fix(lanyard): handle dynamic lanyard path

- .github/workflows/ci.yml
> fix: set `NODE_AUTH_TOKEN`

- src/pure.ts
- test/consent.test.ts
Remove check of experience in config to enable events for custom experiences that do not need a config
Changed test
> fix(plugin): consent event without config

- package-lock.json
- package.json
- src/pure.ts
- test/rights.test.ts
> update User payload and bump deps
> this will be tested once `ketch-tag` version is bumped in `lanyard` and `lanyard` is deployed to staging.
https://ketch-com.atlassian.net/browse/KD-3951
> feat(kd-3951): update User payload and bump deps

- src/pure.ts
> Added capability to trigger show consent Experience from APPs.
> will test it on UAT
> Fix [#1](https://ketch-com.atlassian.net/browse/KD-1987)
> feat(consentExperience) : Added capability to trigger show consent Experience from APPs.

- src/pure.ts
> Incorporate review comments
> will test it on UAT
> Fix [KS-1987](https://ketch-com.atlassian.net/browse/KD-1987)
> fix(ShowConsent) : Incorporate review comments

- package-lock.json
- package.json
- src/pure.ts
> updated ketch-plugin version.
> will test it on UAT
> Fix [KS-1987](https://ketch-com.atlassian.net/browse/KD-1987)
> feat(consentExperience) : updated ketch-plugin version.

- package-lock.json
- package.json
- src/pure.ts
- test/consent.test.ts
> Added method to provision consent.
> will test it on UAT
> Fix [KD-1987](https://ketch-com.atlassian.net/browse/KD-1987)
> feat(consent) : Added method to provision consent.

- package-lock.json
- package.json
- src/pure.ts
Add parameters to showPreferences
> fix(showPreferences): add params

- src/index.ts
- src/pure.ts
- test/preferences.test.ts
> fix(showPreferences): handle no param

- .prettierignore
- .prettierrc
- AUTHORS
- LICENSE
- MAINTAINERS.md
- src/index.ts
- src/internal/datalayer.ts
- src/pure.ts
- test/environment.test.ts
Add `fireNativeEvent`
Unit tests
N/A
> feat(kd-4515): add fireNativeEvent

- package-lock.json
- package.json
- src/internal/parameters.ts
- src/pure.ts
- test/consent.test.ts
> fix(param): preference param

- src/internal/datalayer.ts
- src/pure.ts
> added ketch permit change tealium data layer properties
> tested on local
> https://ketch-com.atlassian.net/browse/KD-4486
> feat(KD-4486): ketch permit change tealium datalayer

- package-lock.json
- package.json
- src/ketch.ts
Switch to functional plugins
N/A
> feat: switch to functional plugins

- src/constants.ts
- src/cookie.ts
- src/newFromBootstrap.ts
Embed plugins
Set SameSite=None and Secure on managed cookies
N/A
N/A
> feat: embed plugins and set SameSite and Secure on managed cookie

- package-lock.json
- package.json
- src/ketch.ts
- src/rights.test.ts
Sync with types and upgrade dependencies
N/A
> fix: sync with types

- jest.config.js
- package-lock.json
- package.json
- src/ketch.ts
- src/rights.test.ts
Fix unit tests
Ran the tests
N/A
> test: fix tests

- package-lock.json
- package.json
> fix: bump future

- src/entrypoint.ts
Make function optional when regex matching
> fix(function): match new format

- src/entrypoint.ts
split properly on function
Local
> fix(function): split properly

- src/ketch.ts
> GPC conset issue
> tested on local
> https://ketch-com.atlassian.net/browse/KD-4968
> fix: GPC conset issue

- src/ketch.ts
This fixes the issue in the event emitter with lost context for the Android webview.
That is a JavaScript binding issue, where the callback we are trying to call looses the this context.
See more details in this thread: 
https://github.com/react-native-webview/react-native-webview/issues/323#issuecomment-511824940
Lets just call the corresponding method directly, without assigning it to local variable.
**Also suggest we log missing handlers as just warnings, we don’t have to register all of them anyway.** 
This should enable events to be fired for Adnroid webview
It can be tested with Android WebView sample app.
https://github.com/ketch-sdk/ketch-samples/pull/22
Steps to reproduce:
1. Run the app in the Android emulator
2. Go to  chrome://inspect in your browser
3. Observe the events …
> Android WebView Java Bridge error fix

- package-lock.json
- package.json
- src/ketch.ts
Filter `this` from `emit` arguments
Unit tests. Full integration testing TBD
Issue with passing `this` to native code
> fix: filter this from emit

- src/ketch.ts
Await config load when registering plugin
> fix(plugin): await config

- src/consent.test.ts
- src/ketch.ts
Do not overwrite server consent values with session consent values
Only augment server consent with unsaved session consent values
Updated unit test
> fix(consent): augment w session only

- package-lock.json
- package.json
- src/ketch.ts
> added recaptchaToken from event to InvokeRight request
> `npm run build` & `npm run test` ran successfully
> [KD-5343](https://ketch-com.atlassian.net/browse/KD-5343)
> fix: added recaptchaToken from event to InvokeRight request

- src/identities.test.ts
- src/ketch.ts
Merge new and old identity
Test case
> fix(identity): merge identity

- src/consent.test.ts
- src/ketch.ts
Handle no purposes returned by backend
> fix(consent): handle empty purpose

- package-lock.json
- package.json
- src/ketch.ts
Handle same origin local storage
> fix(identity): same origin

- .github/workflows/ci.yml
- .prettierignore
- .prettierrc
- docs/classes/Ketch.html
- docs/functions/boot.html
- package-lock.json
- package.json
- src/boot.ts
- src/consent.ts
- tsconfig.json
Remove ncc and produce commonjs module
Unit tests
N/A
> fix: remove ncc

- src/entrypoint.ts
- src/init.ts
- src/ketch.ts
Don't use promise.all for running actions
Docker compose
N/A
> fix: don't use promise.all for running actions

- docs/classes/Ketch.html
- docs/functions/boot.html
- package-lock.json
- package.json
Get latest cookie and cache using tslib for better code size
Unit tests
N/A
> chore: bump dependencies

- .gitattributes
- docs/classes/Ketch.html
- docs/functions/boot.html
- package-lock.json
- package.json
- src/boot.test.ts
- src/boot.ts
- src/consent.test.ts
- src/ketch.ts
- src/ketchfn.ts
- src/test.ts
- test/test.js
- webpack.config.js
Update ketch-types
Unit tests
N/A
> fix: update types

- docs/classes/Ketch.html
- docs/functions/boot.html
- package-lock.json
- package.json
Upgrade ketch-data-layer
Unit tests and in browser manual testing
```
---------------|---------|----------|---------|---------|---------------------------------------------------------------------------------------------------------------------------------
File           | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s                                                                                                               
---------------|---------|----------|---------|---------|---------------------------------------------------------------------------------------------------------------------------------
All files      |   91.31 |    84.69 |   94.95 |   91.25 | …
```
> chore: upgrade ketch-data-layer

- docs/classes/Ketch.html
- docs/functions/boot.html
- package-lock.json
- src/router.test.ts
- src/router.ts
Fix compatibility
Unit tests
N/A
> fix: compatibility

- docs/classes/Ketch.html
- docs/functions/boot.html
- jest.config.js
- src/Ketch.ts
Fix empty config identities
Unit tests
CHANGE-1051
> fix: empty config identities

- src/Ketch.ts
Fix identity Object.keys check
Unit tests
CHANGE-1051
> fix: identity null check

- docs/assets/style.css
- docs/classes/Ketch.html
- docs/functions/boot.html
- jest.config.js
- src/Ketch.ts
- src/constants.ts
Add futures and events for subscriptions
Unit tests
CHANGE-1051
> feat: add futures and events for subscriptions

- docs/classes/Ketch.html
- docs/functions/boot.html
- jest.config.js
- src/Ketch.test.ts
- src/Ketch.ts
Add showSubscriptionTab logic and add logging
Unit tests
CHANGE-1051
> fix: add subscription logging and showing logic

- src/Ketch.ts
More subscription logging
Unit tests
CHANGE-1051
> fix: more subscription logging

- docs/classes/Ketch.html
- docs/functions/boot.html
- src/Ketch.ts
Hide subscriptions tab if set to active and not available
Unit tests
N/A
> fix: hide subscriptions tab if set to active and not available

- jest.config.js
- package-lock.json
- package.json
- src/Ketch_Consent.test.ts
> fix: synthetic response swap orgcode with purposes

- docs/classes/Ketch.html
- docs/functions/boot.html
- package-lock.json
- package.json
- src/Ketch.test.ts
Update data layer to check querystring if not in cookie
Unit tests
N/A
> feat: data layer check querystring if not in cookie

- src/Ketch.ts
updated preferences_tabs logic to honor entitlements
> fix: preferences_tabs

- package-lock.json
- package.json
> fix(logging): bump

- README.md
Due to github shenanigans - the npm package was created but the release was not finished so now github tries to write the already written version number
Create new feature push to bump to new version
> feat(github): force new version

- src/Ketch.ts
> fix GPC opt-out without displaying consent screen issue
> Fix [#1]()
> fix: GPC opt-out without displaying consent screen issue

- src/Builder.test.ts
- src/Builder.ts
> feat(KD-6873): adds condition for Canada region codes;
> chore(KD-6873): adds test case for Canada region codes;
> Integration tests:
> https://ketch-com.atlassian.net/browse/KD-6873
> feat(KD-6873): Adds Canada provinces;

- src/cache.test.ts
- src/cache.ts
> fix(cache): naming

- src/cache.ts
> fix(cache): btoa

- src/cache.ts
Optional localhost + expiry 400 days
> fix(cache): localhost + ttl

- src/Ketch.ts
Add logging for consent identity mismatch
N/A
[KD-8419](https://ketch-com.atlassian.net/browse/KD-8419)
[KD-8419]: https://ketch-com.atlassian.net/browse/KD-8419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: add logging for consent identity mismatch

- docs/classes/Ketch.html
- docs/functions/boot.html
- docs/index.html
- src/Ketch.ts
Add more logging for cached consent
N/A
KD-8419
> fix(KD-8419): add more logging for cached consent

- package-lock.json
- package.json
- src/Builder.test.ts
- src/Ketch.test.ts
- src/Ketch_Consent.test.ts
- src/Ketch_Identities.test.ts
- src/Ketch_Rights.test.ts
- src/cache.test.ts
- src/cache.ts
- src/init.test.ts
Public cookie read canonical purpose codes
Updated unit test
> fix(cache): public canonical purpose codes

- src/Ketch.ts
Always set public consent on fetch consent call
> fix(cache): always set public consent

- package-lock.json
- package.json
> bump ketch-web-api version
> This will be tested in UAT
> https://ketch-com.atlassian.net/browse/KD-9142
> feat(kd-9142): recaptcha on invoke right

- package-lock.json
- package.json
> chore: web api bump

- src/Ketch.ts
Display subscriptions tab if there are no controls
> Fix [#1]()
> fix: no controls

- src/cache.test.ts
- src/cache.ts
> stop saving vendors to the consent cookie
> local/unit test
> https://ketch-com.atlassian.net/browse/KD-10656
> chore: stop saving vendors to the consent cookie

- package-lock.json
- package.json
- src/getApiUrl.ts
> fix(shoreline): web/v3

- src/getApiUrl.ts
> fix(web): condition

- src/Ketch.ts
> fix(config): rm config listener

- package-lock.json
- package.json
- src/InternalRouter.test.ts
- src/InternalRouter.ts
- src/Ketch.ts
- src/Ketch_HasChangedExperience.test.ts
- src/Ketch_HasShownExperience.test.ts
- src/Ketch_WillChangeExperience.test.ts
> chore: bump types dep

- src/Ketch.ts
- src/Ketch_FullConfig.test.ts
- src/Router.test.ts
- src/Router.ts
> fix(config): get full

- package-lock.json
- package.json
- src/Ketch.ts
- src/Ketch_FullConfig.test.ts
Include experience display in full config
> fix(config): exp display

- src/Ketch.ts
> fix(subscriptions): return if no experience

- src/Ketch.ts
> fix(consent): rm extraneous

- package-lock.json
- package.json
> fix: config api no hash

- src/Ketch.ts
> fix(experiencev2): fix subscription

- src/Ketch.ts
Add case to short circuit retrieving subscription if using shoreline v3
> fix(subscription): config v3 compatibility

- src/cache.ts
> fix(cache): rm protocol

- src/cache.ts
> fix(cache): protocol obj

- src/Ketch.test.ts
- src/Ketch.ts
Fix consent merge to only merge purposes
Unit test
> fix(consent): merge

- src/Ketch.ts
> Adds react native post message functions
> Local
> feat: react native post message

- jest.config.js
- src/Builder.ts
- src/constants.ts
- src/getApiUrl.ts
Experience version param
experienceVersion new -> lanyardVersion v2; experienceVersion old -> lanyardVersion v1
experienceVersion new -> shorelineVersion v3; experienceVersion old -> shorelineVersion v2
> fix(init): experience version param

- src/Builder.ts
Catch errors sending telemetry
> fix(telemetry): catch error

- src/Ketch.test.ts
- src/Ketch.ts
- src/__mocks__/webApi.ts
- src/cache.ts
// fire the 'user_consent_change_saved' event when all the following conditions are true
// 1) if the consent is updated by a user (experiences call this changeConsent function so this is true)
// 2) if the consent values have changed (!consentEqual)
// 3) once the server responds confirming that consent has been saved in the database (setConsent promise)
this.emit('user_consent_change_saved', consent)
> fix(consent): consentDidUpdate

- package-lock.json
- package.json
- src/Ketch.test.ts
- src/Ketch.ts
- src/Ketch_Consent.test.ts
- src/Ketch_Preferences.test.ts
- src/Router.ts
- src/Trackers.ts
> fix(setConsent): reason

- src/Ketch.ts
- src/constants.ts
Condition event on purpose equality
Constant + rename
> fix(setConsent): purpose equality event condition

- src/Ketch.ts
> fix(setConsent): fix condition

- package-lock.json
- package.json
- src/Ketch.ts
Option to disable consent capture
locally
https://ketch-com.atlassian.net/browse/KD-12170
https://ketch-com.atlassian.net/browse/KD-12048
> feat: orchestration only

- src/Ketch.ts
Use external consent c instead of api call response consent
> fix(userConsentUpdate): use client consent

- src/Ketch.test.ts
- src/Ketch.ts
Move preference check to lanyard
Add condition for show experience type
> fix(experience): handle new experiences + move checks to lanyard

- src/Ketch.ts
Handle case where the registration of a plugin for a preference event happens after preference event triggered
> fix(preference): handle delayed preference subscription

- src/Ketch.ts
Add hook on on and once events instead of addListenter
> fix(preference): on/once listener

- src/Builder.ts
- src/Ketch.ts
- src/Ketch_Consent.test.ts
- src/cache.test.ts
- src/cache.ts
No cache option to not use consent client side cache
Unit
> fix(consent): no cache option

- package-lock.json
- package.json
Bump data layer
Unit in library
> fix(dataLayer): bump

- src/Builder.test.ts
- src/Builder.ts
Add identities to beacon log query params
Unit tests
> fix(beacon): add identities

- src/Builder.test.ts
- src/Builder.ts
> fixes config fetching for langs such as `fr-CA` that require case sensitivity
> Local w/ unit tests
> https://ketch-com.atlassian.net/browse/KD-12701
> fix: language casing

- package-lock.json
- package.json
Data layer encode
Tests in data layer repo
> fix(dataLayer): encode

- src/Ketch.ts
> Add logs for debugging show consent experience event
> fix: add debug logs

- src/Ketch.ts
> Makes trigger consent/preference functions synchronous
> fix: remove unnecessary async/await

- package-lock.json
- package.json
> bumped deps in future and ketch-tag
> local build
> Fix [#1]()
> fix: upgrades future version, bumps deps

- package-lock.json
- package.json
- src/InternalRouter.test.ts
- src/InternalRouter.ts
> Updates `InternalRouter` for the new getIsExperienceDisplayed method
> Added test to `InternalRouter.test.ts` and ran `npm run test`
> fix: updates internal router

- src/Tags.test.ts
- src/Tags.ts
- src/init.ts
> Manually block/allow html elements based on consent state and attributes added to each element on the customer site
> Tests added in `Tags.test.ts`, run via `npm run test`
> https://ketch-com.atlassian.net/browse/KD-13844
> feat: manual tag blocking

- src/Tags.test.ts
- src/Tags.ts
> Re-execute whenever consent is updated
> https://ketch-com.atlassian.net/browse/KD-13844?searchObjectId=31715&searchContainerId=10000&searchContentType=issue&searchSessionId=c06ea5b7-45fb-4fba-9955-d990d3608e18
> feat: re-execute on consent

- package-lock.json
- package.json
- src/Ketch.ts
- src/Router.ts
Add consent experience options
> fix(experience): consent options

- package-lock.json
- package.json
- src/CookieBlocker.test.ts
- src/CookieBlocker.ts
- src/init.ts
> Deletes browser cookies which match regex patterns specified in the config, if we don't have consent for that cookie
> Added tests in `CookieBlocker.test.ts` and ran using `npm run test`
> https://ketch-com.atlassian.net/browse/KD-13980
> feat: cookie blocking

- src/CookieBlocker.test.ts
- src/CookieBlocker.ts
- src/Tags.test.ts
- src/Tags.ts
> Handle error when consent is undefined
> fix: handle consent being undefined

- package-lock.json
- package.json
- src/Ketch.ts
> fix: proxy

- src/CookieBlocker.test.ts
- src/CookieBlocker.ts
- src/Tags.test.ts
> Retry cookie blocking on consent, adding any new results to the previous set of blocked cookies
> feat(cookie-blocking): retry on consent

- package-lock.json
- package.json
- src/Console.test.ts
- src/Console.ts
- src/CookieBlocker.test.ts
- src/CookieBlocker.ts
- src/Tags.ts
- Removes warning in Console.ts
- Fixes console logging utility in Tags.ts
- Adds handling for non-regex cookies in CookieBlocker.ts
- Fixes vulnerabilities via `npm audit fix`
> `npm run test`, added tests for non-regex cookies in `CookieBlocker.test.ts`
> fix: cookie blocker, tags, console

- src/CookieBlocker.ts
- src/Tags.ts
> Adds domain as this is required to delete cookies which have the domain field set
> npm run test
> Fix [#1]()
> fix: add domain when blocking cookies

- package-lock.json
- package.json
- src/Router.test.ts
- src/Router.ts
Add reinit that calls get consent
> fix: reinit

- src/Ketch.ts
- src/Router.test.ts
- src/Router.ts
> fix: reinit reset consent

- src/Ketch.ts
Reset identities in reset consent
> fix: identity reset

- src/Ketch.ts
> fix: restart identity watchers
