ketch-sdk/ketch-tag

src/pure.ts, test/preferences.test.ts
Fixes the signature of the consent object to always be consistent and always have "purposes" and "vendors".
Unit tests
N/A
=> fix: signature of consent object

package-lock.json, package.json, src/pure.ts, test/consent.test.ts, test/rights.test.ts
Update invokeRights to use a single rightCode per shoreline spec
Include switchbitPermitChanged for backwards compatibility
Update tests
=> fix(invokeRight): rightCode + swbPermit backward compatibility

src/pure.ts
Merge consent retrieved from the server with consent stored in the client side session to ensure that consent is consistent within a client session
Midigate users seeing recurring experience
=> feat(consent): store and merge session consent

package-lock.json, package.json, src/consent.test.ts, src/ketch.ts, src/parameters.ts
Add parameters to show preferences and select a preference tab
Moved from closed branch https://github.com/ketch-sdk/ketch-tag/pull/248
=> fix(preferences): param to show

jest.config.js, src/ketch.ts
Race condition with empty local consent was causing the user to always be reprompted with the banner because the server consent and the local consent did not match. If the local consent is empty that means that the user has not yet made a consent selection so short circuit and return identities
=> fix(consent): do not reprompt if no yet set

src/ketch.ts
> Right now, strings are serialized into the string inside a string, arriving as `""aadadda""`, we have to strip the redundant quotation marks. This change handle string as a single argument without JSON serialization for webview callback
It can be tested with Android WebView sample app.
https://github.com/ketch-sdk/ketch-samples/pull/22
Steps to reproduce:
1. Run the app in the Android emulator
2. Go to  chrome://inspect in your browser
3. Observe the events fired in the console
String arguments arrive should arrive as regular strings without quotation marks, for ex. callbacks like `tcf_updated`.
=> fix: strings in native callbacks

src/Ketch.ts
This is a customer use case for extracting the identity from a Google Analytics cookie
The cookie is formatted as GA1.2.123.123 or GA1.1.123.123 where the first version is set by universal analytics
and the second version is set by GA4. Some customers have both tags on the page leading to inconsistent identity.
// this is a solution for customers who use the Google Analytics identifier as their primary identity space
// with the identity space code google_analytics_cookie
=> fix(identity): google analytics id trim

src/Builder.ts
> Fastly documentation recommends using query params instead of request body.  Hence this change.
> All in all, and especially considering the bug in Chrome, we recommend constructing a [URLSearchParams]
> (https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) and simply serializing it on the end of the beacon URL as shown above.
> To be tested after updating semaphore
> Fix [#1]()
=> chore: use query strings

src/Ketch.ts, src/Ketch_Preferences.test.ts, src/constants.ts
> https://ketch-com.atlassian.net/browse/KD-12109
> Preferences experience should not exit w/ error when no purposes are found
> Instead, hide the consents tab
>Local
>https://ketch-com.atlassian.net/browse/KD-12109
=> fix: handle no purposes error in showPreferencesExperience

src/Ketch.ts, src/Ketch_Rights.test.ts
Use a copy of the in-memory identities for right invocations and then add the email identity to that identity list copy. This ensures that a consent call that happens right after a right invocations request does not accidentally have an email identity in there, which was happening because the right invocation request was mutating the in-memory identity list that the consent call was using.
Unit tested, all existing tests passed and also added a new test case which passed as well
https://ketch-com.slack.com/archives/C02GA8GJAR5/p1709929343214609?thread_ts=1703028789.368009&cid=C02GA8GJAR5
=> fix(ketch-tag): use copy of in-memory identities for right invocations

package-lock.json, src/Trackers.test.ts, src/Trackers.ts, src/init.ts
- Override and provide consent so respective tag managers triggers all tags thereby allowing all trackers to be scanned
- Has no impact on current user flows
locally
https://ketch-com.atlassian.net/browse/KD-12047
https://ketch-com.atlassian.net/browse/KD-12048
=> feat: allow all trackers by overriding consent

src/init.ts
> Adds `?` for case when window.localStorage is null, which can happen in certain mobile webview implementations
> https://ketch-com.slack.com/archives/C02EWFDVD71/p1712079195954359
=> fix: handle case where window.localStorage is null

package-lock.json, package.json, src/Ketch.ts
> instruct ketch-tag to close the experience without overriding consent that may have been updated by a submitted dsr
> Local
> https://ketch-com.atlassian.net/browse/KD-13064
=> fix: add support for CLOSE_WITHOUT_SETTING_CONSENT

src/InternalRouter.ts, src/Ketch.ts
> Calls setConsent in experienceClosed when reason === setConsent
> All existing tests passed
=> fix: setConsent in experienceClosed

src/Ketch.ts
> Waits for consent listener to be registered before calling `willShowExperience` and emitting the `showConsentExperience` event
> https://ketch-com.atlassian.net/browse/KD-12941 and https://ketch-com.atlassian.net/browse/KD-12943
=> fix(consent): wait for consent listener before triggering consent experience

src/Ketch.test.ts, src/Ketch.ts
> Adds a method which returns the value of `Ketch._getIsExperienceDisplayed`
> Added test in `Ketch.test.ts` for this new method
> https://ketch-com.atlassian.net/browse/KD-13653
=> feat: getIsExperienceDisplayed method

src/Tags.ts
> Reworks the `Tags.execute()` function to store the results of which tags were allowed vs. blocked, so that we can report them via the console `KetchLog.getWrappedTags()` function
> https://ketch-com.atlassian.net/browse/KD-13844?searchObjectId=31715&searchContainerId=10000&searchContentType=issue&searchSessionId=b3f3ff10-ffb2-4cae-a609-c8111ab81615
=> refactor: store tag blocking results to facilitate console logging function

src/CookieBlocker.test.ts, src/CookieBlocker.ts
> Trims whitespace on cookie string, currently there is a single whitespace on each one causing none of the regular expressions to match
> Added two tests in `CookieBlocker.test.ts` and ran via `npm run test`
=> fix: trim cookie name

src/Ketch.ts, src/__mocks__/webApi.ts
> Ensures that this._isExperienceDisplayed is not set when there is no experiences of the type (consent or preference) in the config
> `npm run test`, updated mock of empty config to include experiences
> https://ketch-com.atlassian.net/browse/KD-13215
=> fix: don't set isExperienceDisplayed when no experiences in config

src/CookieBlocker.test.ts, src/CookieBlocker.ts, src/Tags.ts
> Re-execute when the DOMContentLoaded event fires, which is when any non-async or dynamically loaded scripts have finished executing
> Added test in CookieBlocker.test.ts
>
=> feat(cookie-blocking): re-execute when DOMContentLoaded fires
